name: Refresh Enedis OAuth Token

on:
  schedule:
    - cron: '0 */3 * * *'    # toutes les 3 heures, minute 0
  workflow_dispatch:        # permet le déclenchement manuel

jobs:
  refresh-token:
    runs-on: ubuntu-latest

    # <-- ces deux variables sont injectées depuis vos Secrets GitHub
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Call Supabase Edge Function to refresh token
        run: |
          curl -X POST "$SUPABASE_URL/functions/v1/enedis-active-token" \
            -H "Content-Type: application/json" \
            -H "apiKey: $SUPABASE_SERVICE_ROLE_KEY" \
            -d '{}' \
            --fail
