name: Refresh Enedis OAuth Token

on:
  schedule:
    - cron: '0 */3 * * *'   # toutes les 3 heures, minute 0
  workflow_dispatch:       # pour un lancement manuel

jobs:
  refresh-token:
    runs-on: ubuntu-latest

    steps:
      - name: Call Supabase Edge Function to refresh token
        run: |
          curl -X POST "$SUPABASE_URL/functions/v1/enedis-active-token" \
            -H "Content-Type: application/json" \
            -H "apiKey: $SUPABASE_SERVICE_ROLE_KEY" \
            -d '{}' \
            --fail
