name: Refresh Enedis OAuth Token

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  refresh-token:
    runs-on: ubuntu-latest

    steps:
      - name: Test direct call (contournement)
        run: |
          # On hardcode l'URL directement pour voir si curl passe
          echo "Calling: https://xpxbxfuckljqdvkajlmx.supabase.co/functions/v1/enedis-active-token"
          curl -X POST "https://xpxbxfuckljqdvkajlmx.supabase.co/functions/v1/enedis-active-token" \
            -H "Content-Type: application/json" \
            -H "apiKey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -d '{}' \
            --fail
